import type { Command } from "@commander-js/extra-typings";
import { MenvError } from "../core/errors.ts";

// Walk the live commander tree, so completions cannot drift from the grammar:
// new commands/flags appear automatically. The drift-guard test still asserts
// coverage to catch an emit bug.
export function walkCommands(program: Command): { commands: string[]; flags: string[] } {
  const commands: string[] = [];
  const flags = new Set<string>();
  for (const o of program.options) if (o.long !== undefined) flags.add(o.long);
  const recurse = (cmd: Command, prefix: string[]): void => {
    for (const sub of cmd.commands as Command[]) {
      const path = [...prefix, sub.name()];
      commands.push(path.join(" "));
      for (const o of sub.options) if (o.long !== undefined) flags.add(o.long);
      recurse(sub, path);
    }
  };
  recurse(program, []);
  return { commands: commands.sort(), flags: [...flags].sort() };
}

export function emitZsh(program: Command): string {
  const { commands, flags } = walkCommands(program);
  const cmdArr = commands.map((c) => `'${c}'`).join(" ");
  const flagArr = flags.map((f) => `'${f}'`).join(" ");
  return [
    "#compdef menv",
    "# menv zsh completion — generated by `menv completions zsh`.",
    "# Install: menv completions zsh > \"${fpath[1]}/_menv\"  (or: source <(menv completions zsh))",
    "_menv() {",
    `  local -a _menv_cmds=(${cmdArr})`,
    `  local -a _menv_flags=(${flagArr})`,
    "  _arguments '1: :->cmd' '*: :->rest'",
    "  case $state in",
    "    cmd)  compadd -- ${_menv_cmds%% *} ;;",
    "    rest) compadd -- $_menv_flags ${_menv_cmds} ;;",
    "  esac",
    "}",
    "compdef _menv menv",
    "",
  ].join("\n");
}

export function emitBash(program: Command): string {
  const { commands, flags } = walkCommands(program);
  const words = [...new Set([...commands.flatMap((c) => c.split(" ")), ...flags])].sort().join(" ");
  return [
    "# menv bash completion — generated by `menv completions bash`.",
    "# Install: source <(menv completions bash)",
    "# Commands: " + commands.join(", "),
    "_menv() {",
    '  local cur="${COMP_WORDS[COMP_CWORD]}"',
    `  COMPREPLY=( $(compgen -W "${words}" -- "$cur") )`,
    "}",
    "complete -F _menv menv",
    "",
  ].join("\n");
}

export function emitCompletions(program: Command, shell: string): string {
  if (shell === "zsh") return emitZsh(program);
  if (shell === "bash") return emitBash(program);
  throw new MenvError("VALIDATION", `unsupported shell "${shell}" (zsh | bash)`);
}
